<div style="background-color: black;">
<hr style="border: 3px solid skyblue;">
<div style="text-align: center; margin-left: 0em; font-weight: bold; font-size: 20px; font-family: TimesNewRoman; color: skyblue; text-transform: uppercase;">
    TIME SERIES DATA PROCESSING
    <br>
    LOAD REAL TIME | LOAD DAY AHEAD
</div>
<div style="text-align: center; margin-left: 0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color: skyblue">
Fulfilling Missed Time Steps Notebook
</div>
<div style="text-align: justify; margin-left: 0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color: skyblue">
        Each part of the following script was used for the pacially processed time series i.e. Availability Factors, Scalled Inflows, Current Load and Load Dayahead data, to fill al those missing time steps, or point points that do not content any value or falling that, content N/A, n/e or '0' value.
<br>
Read explanation text cells to follow and understand all the process until final results were got stept by step.
</div>
    <hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    1. Notebook Set Up
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Importing needed libraries
</div>

In [6]:
import pandas as pd
from entsoe import EntsoePandasClient
from entsoe.exceptions import NoMatchingDataError  # Ensure this line is included
from entsoe.exceptions import NoMatchingDataError, InvalidBusinessParameterError  # Import relevant exceptions
import os
import csv
from datetime import datetime
import pytz
from pytz import timezone, utc
import shutil
from functools import lru_cache
from concurrent.futures import ProcessPoolExecutor

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    2. Dispa-SET_Unleash Folder Path
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Determinning dynamically the zone_folder_path based on the location of the "Dispa-SET_Unleash" folder relative to the current working directory.
</div>
<div style="text-align: justify; margin-left: 2.0em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman; color:skyblue">
- If the "Dispa-SET_Unleash" folder is copied to a different machine or location, the dispaSET_unleash_folder_path variable will automatically adjust accordingly.
</div>

In [11]:
# Get the current working directory
current_directory = os.getcwd()

# Navigate to the parent directory of "Dispa-SET_Unleash"
dispaSET_unleash_parent_directory = os.path.dirname(current_directory)

# Get the path to the "Dispa-SET_Unleash" folder
dispaSET_unleash_folder_path = os.path.dirname(dispaSET_unleash_parent_directory)

# Construct the dispaSET_unleash_folder_name variable
dispaSET_unleash_folder_name = os.path.basename(dispaSET_unleash_folder_path)

print("dispaSET_unleash_folder_name:", dispaSET_unleash_folder_name)
print("dispaSET_unleash_folder_path:", dispaSET_unleash_folder_path)

dispaSET_unleash_folder_name: Dispa-SET_Unleash
dispaSET_unleash_folder_path: /home/ray/Dispa-SET_Unleash

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    3. Usefull Variable Definition
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Entering a value to all the variables which content are going to be used in some of the next stages of this script. 
</div>
<div style="text-align: Justify; margin-left: 2.0em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman; color:skyblue">
Indicate the year of all data is referring to in the variable data_year.
<br>
The universal_standar_time variable is going to be used to download all the time series data in this horary zone. Additionally as each european country belongs a particular time sector the corresponding time series data related to its time sector are going to be downloaded as well but in a different file.
<br>Additionally there are some default parameters that has to be defined to the correct working and calling to the ENTSO-E downloading functions.
</div>

In [12]:
# Year to which data refers to:
data_years_list = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

In [13]:
# Additional string to be appended
#availability_factors_folder_path = dispaSET_unleash_folder_path + "\Database\AvailabilityFactors"
load_dayahead_folder_path = dispaSET_unleash_folder_path + "\Database\Load_DayAhead"
load_realtime_folder_path = dispaSET_unleash_folder_path + "\Database\Load_RealTime"
#scalled_inflows_folder_path = dispaSET_unleash_folder_path + "\Database\HydroData\ScaledInflows"

#print("availability_factors_folder_path:", availability_factors_folder_path)
print("load_dayahead_folder_path:", load_dayahead_folder_path)
print("load_realtime_folder_path:", load_realtime_folder_path)
#print("scalled_inflows_folder_path:", scalled_inflows_folder_path)

load_dayahead_folder_path: /home/ray/Dispa-SET_Unleash\Database\Load_DayAhead
load_realtime_folder_path: /home/ray/Dispa-SET_Unleash\Database\Load_RealTime

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    4. Missed Values Fulfilling
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Because of the data from the original sources, there are some time points that might have the value of '0'.
<br>
This missed points are completed using the data from previous years.
</div>

In [14]:
def adjust_year_in_timestamp(timestamp, new_year):
    """
    Adjust the year in the timestamp to the new year, keeping the same date and time structure.
    """
    dt = datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S+00:00')
    return dt.replace(year=new_year).strftime('%Y-%m-%d %H:%M:%S+00:00')

def find_value_in_other_files(target_year, target_timestamp, dataframes, data_years_list, search_previous=True):
    """
    Search for the target timestamp in previous or next CSV files to find a value greater than 0.
    If search_previous is True, look in previous years, otherwise look in future years.
    """
    current_year_index = data_years_list.index(target_year)
    
    if search_previous:
        search_range = range(current_year_index - 1, -1, -1)  # Previous years
    else:
        search_range = range(current_year_index + 1, len(data_years_list))  # Future years
    
    for index in search_range:
        other_year = data_years_list[index]
        df_other = dataframes[other_year]
        
        # Adjust the timestamp to match the year of the other file
        adjusted_timestamp = adjust_year_in_timestamp(target_timestamp, other_year)
        
        # Look for the adjusted timestamp in the first column (index)
        if adjusted_timestamp in df_other.index:
            value = df_other.loc[adjusted_timestamp, df_other.columns[1]]  # Second column value
            if value > 0:  # If value is greater than 0, return it
                print(f"Found value {value} in {other_year}.csv for timestamp {adjusted_timestamp}")
                return value
        else:
            print(f"{other_year}.csv does not contain the timestamp {adjusted_timestamp}, skipping...")
    
    return None  # If no value is found, return None

def process_csv_files(data_years_list, load_realtime_folder_path):
    """
    Process all CSV files in the specified folder structure.
    """
    dataframes = {year: None for year in data_years_list}
    
    # Load all relevant CSV files into memory
    for year in data_years_list:
        file_path = os.path.join(load_realtime_folder_path, f"{year}.csv")
        if os.path.exists(file_path):
            df = pd.read_csv(file_path)
            df.columns = df.columns.str.strip()  # Clean column names
            df.set_index(df.columns[0], inplace=True)  # Set timestamp as index
            dataframes[year] = df
            print(f"Loaded file: {file_path}")
        else:
            print(f"File {file_path} does not exist, skipping...")

    # Now process the loaded DataFrames
    for root, dirs, files in os.walk(load_realtime_folder_path):
        for file in files:
            if file.endswith('.csv'):
                year = int(file.split('.')[0])
                if year in data_years_list:
                    df = dataframes[year]
                    
                    # Loop through rows where the second column has a value of '0'
                    for idx in df[df[df.columns[1]] == 0].index:
                        target_timestamp = idx  # Use index directly as timestamp
                        print(f"Found '0' value at row {idx}, timestamp: {target_timestamp}. Searching for replacement...")
                        
                        new_value = None
                        # Try searching in previous years first
                        new_value = find_value_in_other_files(year, target_timestamp, dataframes, data_years_list, search_previous=True)
                        
                        if new_value is None:  # If no value was found in previous years, search future years
                            new_value = find_value_in_other_files(year, target_timestamp, dataframes, data_years_list, search_previous=False)
                        
                        if new_value is not None:
                            df.at[idx, df.columns[1]] = new_value
                            print(f"Replaced '0' value at row {idx} with {new_value}.")
                        else:
                            print(f"No replacement found for row {idx}, keeping original '0' value.")
                    
                    # Save the modified DataFrame back to the CSV file
                    df.to_csv(os.path.join(root, file), index=True)
                    print(f"File {file_path} updated successfully.")
                else:
                    print(f"Year {year} not in data_years_list, skipping {file_path}.")

process_csv_files(data_years_list, load_realtime_folder_path)

File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2016.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2017.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2018.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2019.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2020.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2021.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2022.csv does not exist, skipping...
File /home/ray/Dispa-SET_Unleash\Database\Load_RealTime/2023.csv does not exist, skipping...

<div style="background-color: black;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
There remain some missed points that do not have any value even for all the analized years.
<br>
This missed points are completed using the data from the closest time step in the same hour inside the analized year.
</div>

In [13]:
def is_leap_year(year):
    """Check if a year is a leap year."""
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

def adjust_year_in_timestamp(timestamp, new_year):
    """
    Adjust the year in the timestamp to the new year, keeping the same date and time structure.
    If the date is February 29 and the new year is not a leap year, adjust to February 28.
    """
    dt = datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S+00:00')
    
    # If the original date is February 29 and the new year is not a leap year, adjust to February 28
    if dt.month == 2 and dt.day == 29 and not is_leap_year(new_year):
        return dt.replace(year=new_year, day=28).strftime('%Y-%m-%d %H:%M:%S+00:00')
    
    return dt.replace(year=new_year).strftime('%Y-%m-%d %H:%M:%S+00:00')

def find_next_valid_value(df, start_idx, target_time):
    """
    Look for the next non-zero value in the same file that has the same hour as the target_time.
    """
    target_hour = datetime.strptime(target_time, '%Y-%m-%d %H:%M:%S+00:00').hour
    
    for idx in range(start_idx + 1, len(df)):
        next_timestamp = df.iloc[idx, 0]
        next_value = df.iloc[idx, 1]
        
        # Extract the hour from the next timestamp
        next_hour = datetime.strptime(next_timestamp, '%Y-%m-%d %H:%M:%S+00:00').hour
        
        # If the hour matches and the value is greater than 0, return the value
        if next_hour == target_hour and next_value > 0:
            return next_value
    
    return None  # No valid value found in the current file

def process_csv_file(file_path, year):
    """
    Process a single CSV file, looking for 0 values and replacing them with the next valid value.
    """
    if os.path.exists(file_path):
        print(f"Processing file: {file_path}")
        
        # Load the CSV without headers
        df = pd.read_csv(file_path, header=None)
        
        # Assign default column names (since there are no headers)
        df.columns = ['Timestamp', 'Value']
        
        # Loop through rows where the second column (Value) has a value of '0'
        for idx, row in df[df['Value'] == 0].iterrows():
            target_timestamp = row['Timestamp']  # First column (Timestamp)
            
            # Find the next valid value in the current file
            new_value = find_next_valid_value(df, idx, target_timestamp)
            
            if new_value is not None:
                # Update the value in the DataFrame
                df.at[idx, 'Value'] = new_value
                print(f"Replaced '0' value at row {idx} with {new_value}.")
            else:
                print(f"No valid replacement found for row {idx}, keeping original '0' value.")
        
        # Save the modified DataFrame back to the CSV file (without headers)
        df.to_csv(file_path, index=False, header=False)
        print(f"File {file_path} updated successfully.")
    else:
        print(f"File {file_path} does not exist, skipping...")

def process_csv_files_in_directory(directory_path, data_years_list):
    """
    Process CSV files in a specific sub-directory (like '1h', '30min', or '15min').
    """
    for year in data_years_list:
        file_path = os.path.join(directory_path, f"{year}.csv")
        process_csv_file(file_path, year)

def process_all_csv_files(load_realtime_folder_path, data_years_list):
    """
    Recursively go through all sub-folders in the load_realtime_folder_path, find '1h', '30min', and '15min' folders,
    and process the CSV files inside.
    """
    for root, dirs, files in os.walk(load_realtime_folder_path):
        for subdir in ['1h', '30min', '15min']:
            subdir_path = os.path.join(root, subdir)
            if os.path.exists(subdir_path):
                print(f"Processing CSV files in folder: {subdir_path}")
                process_csv_files_in_directory(subdir_path, data_years_list)
            else:
                print(f"Sub-folder {subdir} does not exist in {root}, skipping...")

# Example usage
load_realtime_folder_path = load_realtime_folder_path  # Replace with your actual directory path

process_all_csv_files(load_realtime_folder_path, data_years_list)

Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime, skipping...
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h\2023.csv updated successfully.
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min\2023.csv updated successfully.
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min\2023.csv updated successfully.
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\15min, skipping...
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\1h, skipping...
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\AT\30min, skipping...
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h\2023.csv updated successfully.
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min\2023.csv updated successfully.
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min\2023.csv updated successfully.
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\15min, skipping...
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\1h, skipping...
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BE\30min, skipping...
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2016.csv
No valid replacement found for row 8783, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2017.csv
No valid replacement found for row 8759, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2018.csv
No valid replacement found for row 8759, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2019.csv
No valid replacement found for row 8759, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2020.csv
No valid replacement found for row 8783, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2021.csv
No valid replacement found for row 8759, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2022.csv
No valid replacement found for row 8759, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2023.csv
No valid replacement found for row 8759, keeping original '0' value.
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h\2023.csv updated successfully.
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG, skipping...
Sub-folder 1h does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h, skipping...
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h, skipping...
Sub-folder 15min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\BG\1h, skipping...
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2016.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2016.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2017.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2017.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2018.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2018.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2019.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2019.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2020.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2020.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2021.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2021.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2022.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2022.csv updated successfully.
Processing file: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2023.csv
File C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\1h\2023.csv updated successfully.
Sub-folder 30min does not exist in C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH, skipping...
Processing CSV files in folder: C:\Users\ray.rojas\Documents\GitHub\Dispa-SET_Unleash\Database\Load_RealTime\CH\15min

KeyboardInterrupt: